version: '3'
services:
  app:
    container_name: todo_app
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev
    restart: always
    networks:
      - default
    depends_on:
      - db
  db:
    container_name: db
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/sqlite3
    restart: always
    networks:
      - default

volumes:
  db-volume:

networks:
  default:
    driver: bridge
